name: emo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.14
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - ascii-animator==0.1.8
      - ascii-magic==1.6
      - asciimatics==1.15.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.5.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-default-group==1.2.4
      - cloudpickle==3.0.0
      - cloup==2.1.2
      - colorama==0.4.6
      - colorlog==6.8.2
      - comet-ml==3.43.2
      - configobj==5.0.8
      - contourpy==1.2.0
      - cursor==1.3.5
      - cycler==0.12.1
      - datasets==2.19.1
      - defusedxml==0.7.1
      - dgl==2.1.0
      - dill==0.3.8
      - dm-tree==0.1.8
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docwriter==1.3.3
      - dulwich==0.22.1
      - email-validator==2.2.0
      - et-xmlfile==1.1.0
      - everett==3.1.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - ffmpy==0.3.2
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - fonttools==4.50.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.6.0
      - ghp-import==2.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glcontext==2.5.0
      - google-auth==2.34.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - gradio==3.50.0
      - gradio-client==0.6.1
      - greenlet==3.0.3
      - grpcio==1.62.2
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - idna==3.6
      - imageio==2.34.1
      - imbalanced-learn==0.12.3
      - importlib-resources==6.4.0
      - ipdb==0.13.13
      - isoduration==20.11.0
      - isosurfaces==0.1.0
      - jinja2==3.1.3
      - joblib==1.4.0
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - keras==2.15.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.6
      - list2term==0.1.6
      - mako==1.3.5
      - manim==0.18.0.post0
      - manimpango==0.5.0
      - mapbox-earcut==1.0.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mistune==2.0.5
      - mkdocs==1.5.3
      - mkdocs-material==9.5.15
      - mkdocs-material-extensions==1.3.1
      - ml-dtypes==0.2.0
      - moderngl==5.10.0
      - moderngl-window==2.4.4
      - mpmath==1.2.1
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - namex==0.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optree==0.12.1
      - optuna==3.6.1
      - orjson==3.10.6
      - overrides==7.7.0
      - paginate==0.5.6
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - pillow==9.5.0
      - plotly==5.22.0
      - prometheus-client==0.20.0
      - protobuf==4.25.4
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycairo==1.26.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyfiglet==1.0.2
      - pyglet==2.1.dev2
      - pymdown-extensions==10.7.1
      - pyparsing==3.1.2
      - pyrr==0.10.3
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.9
      - pytorch-lightning==2.3.3
      - pytorch-triton==3.0.0+45fff310c8
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyyaml-env-tag==0.1
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.5.1
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.4.2
      - scipy==1.12.0
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==3.0.1
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - simplejson==3.19.2
      - skia-pathops==0.7.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - soupsieve==2.5
      - sqlalchemy==2.0.32
      - srt==3.5.3
      - starlette==0.37.2
      - svgelements==1.9.6
      - sympy==1.12
      - tenacity==8.5.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.23.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tifffile==2024.7.2
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.4.0.dev20240429+cu121
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt23cu121
      - torchaudio==2.2.0.dev20240429+cu121
      - torchdata==0.7.1
      - torchgeometry==0.1.2
      - torchmetrics==1.4.0.post0
      - torchvision==0.19.0.dev20240429+cu121
      - tornado==6.2
      - tqdm==4.66.2
      - transformers==4.40.2
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==2.2.1
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - wandb==0.17.5
      - watchdog==3.0.0
      - watchfiles==0.22.0
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.2
      - wrapt==1.14.1
      - wurlitzer==3.1.1
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.9.4
